supplier: dto.supplier || undefined,
assignedUser: dto.assignedUser || undefined,
responsible: dto.responsible || undefined,
ipAddress: dto.ipAddress || undefined,
macAddress: dto.macAddress || undefined,
remoteAccess: dto.remoteAccess || undefined,
extraFields: dto.extraFields ? (Array.isArray(dto.extraFields) ? dto.extraFields : []) : undefined,
